language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database phantom_test;' -U postgres
script: npm run test
after_success: npm run coverage
