env:
  global:
    - CC_TEST_REPORTER_ID=5a2e4619896eb6f574ab6d98089b42915bfaaccb642c17c997a71c18920343d4
language: node_js
node_js:
  - '12'
before_install:
  - npm install sequelize-cli -g
install:
  - npm install
services:
  - postgresql
before_script:
  - npm add sequelize-cli
  - psql -c 'CREATE DATABASE phantom_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm test
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run coverage
